
movement_controller:
  ros__parameters:
    target_height : 0.09
    move_time : 4.0
    search_size: 0.2

vision_node:
  ros__parameters:
    space_angle: 90.0
    camera_height: 30.0

usb_cam_node:
  ros__parameters:
    video_device: /dev/video4